---
title: "Assignment 1: Introduction"
author: "Ayden Schirmacher"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have limited data analytics experience, having used Excel mostly in course labs and in Fundamentals of GIS last semester. My R experience is limited to having taken 710 Statistics last semester. I wanted to take this course because while I understand R and can use it, I felt that learning R in that course went a bit fast for me and i relied too heavily on the internet to help me finish assignments without internalizing what we were learning. I have no experience in Git. 

2. Are there any components of the course about which you feel confident?

> Answer: I know my way around the R interface pretty well and can remember some of the commands in R-code. I am pretty confident in my ability to understand data and in my statistics skills.  

3. Are there any components of the course about which you feel apprehensive?

> Answer: Not apprehensive necessarily but want to really cement R skills so that I can work with datasets and code and not have to check everything I do. I want to be able to troubleshoot for myself. 


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/schirmaa7/EDA_Spring2025/tree/main

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
